### ISSUE TITLE
hi, I have a problem. Could you help me?

### ISSUE THREAD

**Issue by gml100** [Plumess/A-Cross-scale-Framework-for-Low-light-Image-Enhancement-Using-Spatial-spectral-Infomation#1]
I try run my dataset,but it has son error. Could you help me?
C:\Users\lenovo\.conda\envs\pt\python.exe H:/00_Gao/ACSF/main_LOL.py
C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
#parameters:  8112817
load weights successfully
train_input_image 60
number of test samples: 60
low_in_shape: torch.Size([1, 3, 384, 384])
Traceback (most recent call last):
  File "H:/00_Gao/ACSF/main_LOL.py", line 176, in <module>
    main()
  File "H:/00_Gao/ACSF/main_LOL.py", line 168, in main
    test()
  File "H:/00_Gao/ACSF/main_LOL.py", line 147, in test
    S_low = enhancenet(low_im)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 675, in forward
    ffc1 = self.ffc1(l1)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 643, in forward
    l1 = self.lewin1(input)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 562, in forward
    attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, win_size*win_size, C
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 139, in forward
    q, k, v = self.qkv(x, attn_kv)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 91, in forward
    q = self.to_q(x)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\00_Gao\ACSF\model_LOL.py", line 64, in forward
    x = self.depthwise(x)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\lenovo\.conda\envs\pt\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
Process finished with exit code 1
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)

**Comment by Plumess** [comment]
Hello,

To better assist you with the error you've encountered, could you please provide more details about your setup? Specifically:

Python Version: What Python version are you using?
PyTorch Version: What's the version of PyTorch installed?
CUDA Version: If using GPU, what's your CUDA version?
Dataset: Are you using the LOL test images provided by the project?
Pre-trained Model and Path: Did you correctly choose the pre-trained model and its path?
This information will help diagnose the issue more accurately. Thank you!


您好，

为了更好地帮助您解决遇到的错误，能否请您提供一些关于您的设置的详细信息？具体包括：

Python版本：您使用的Python版本是什么？
PyTorch版本：安装的PyTorch版本是多少？
CUDA版本：如果使用GPU，您的CUDA版本是什么？
数据集：您是否使用项目提供的LOL数据集？
预训练模型及路径：您是否正确选择了预训练模型及其路径？
提供这些信息将有助于我们更准确地诊断问题。谢谢！

PS: 如果您是中文使用者，可以直接使用中文进行沟通。
